# Generated by Django 5.2 on 2026-06-22 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activity',
            name='action',
            field=models.CharField(choices=[('create_board', 'Creó tablero'), ('create_card', 'Creó tarea'), ('delete_card', 'Eliminó tarea'), ('move_card', 'Movió tarea'), ('edit_card', 'Editó tarea'), ('add_comment', 'Comentó'), ('create_list', 'Creó lista'), ('delete_list', 'Eliminó lista'), ('add_member', 'Agregó miembro'), ('remove_member', 'Eliminó miembro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('card_assigned', 'Tarea asignada'), ('new_comment', 'Nuevo comentario'), ('card_moved', 'Tarjeta movida'), ('member_added', 'Miembro agregado'), ('card_deleted', 'Tarjeta eliminada')], max_length=20),
        ),
    ]
