# Generated by Django 5.2 on 2026-06-29 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_activity_action'),
        ('notifications', '0002_notification_sender_alter_activity_action_and_more'),
    ]

    operations = [
    ]
