# Generated by Django 5.2 on 2026-06-30 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_merge_20260629_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='contact_request_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('card_assigned', 'Tarea asignada'), ('new_comment', 'Nuevo comentario'), ('card_moved', 'Tarjeta movida'), ('member_added', 'Miembro agregado'), ('card_deleted', 'Tarjeta eliminada'), ('contact_request', 'Solicitud de contacto')], max_length=20),
        ),
    ]
