# Generated by Django 5.2 on 2026-05-24 20:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del tablero (mínimo 3 caracteres)', max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
                ('description', models.TextField(blank=True, help_text='Descripción opcional del tablero', null=True)),
                ('is_archived', models.BooleanField(default=False, help_text='Indica si el tablero está archivado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='Usuario propietario del tablero', on_delete=django.db.models.deletion.CASCADE, related_name='owned_boards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tablero',
                'verbose_name_plural': 'Tableros',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de la lista (ej: To Do, In Progress)', max_length=100, validators=[django.core.validators.MinLengthValidator(1)])),
                ('position', models.DecimalField(decimal_places=2, default=0, help_text='Posición para ordenar las listas (Decimal permite inserción flexible)', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('board', models.ForeignKey(help_text='Tablero al que pertenece esta lista', on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='boards.board')),
            ],
            options={
                'verbose_name': 'Lista',
                'verbose_name_plural': 'Listas',
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título de la tarea', max_length=200, validators=[django.core.validators.MinLengthValidator(3)])),
                ('description', models.TextField(blank=True, help_text='Descripción detallada de la tarea')),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', help_text='Prioridad de la tarea', max_length=10)),
                ('due_date', models.DateTimeField(blank=True, help_text='Fecha límite para completar la tarea', null=True)),
                ('position', models.DecimalField(decimal_places=2, default=0, help_text='Posición para ordenar tarjetas dentro de la lista', max_digits=10)),
                ('is_completed', models.BooleanField(default=False, help_text='Indica si la tarea está completada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Usuario asignado a esta tarea', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cards', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(help_text='Usuario que creó la tarjeta', on_delete=django.db.models.deletion.CASCADE, related_name='created_cards', to=settings.AUTH_USER_MODEL)),
                ('list', models.ForeignKey(help_text='Lista Kanban donde se encuentra la tarjeta', on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='boards.list')),
            ],
            options={
                'verbose_name': 'Tarjeta',
                'verbose_name_plural': 'Tarjetas',
                'ordering': ['position', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('member', 'Miembro'), ('viewer', 'Espectador')], default='member', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.board')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membresía',
                'verbose_name_plural': 'Membresías',
                'unique_together': {('user', 'board')},
            },
        ),
        migrations.AddField(
            model_name='board',
            name='members',
            field=models.ManyToManyField(help_text='Miembros colaboradores del tablero', related_name='boards', through='boards.Membership', to=settings.AUTH_USER_MODEL),
        ),
    ]
